base_probe/test_adding_blacklisted.sh: Adapt to another error message
Current error message looks like:

  Failed to find scope of probe point.
  fs_label is out of .text, skip it.
    Error: Failed to add events.

We need to accept it.